name: Snowflake Test and Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-bench:
    runs-on: ubuntu-latest
    outputs:
      test_status: ${{ steps.set-status.outputs.status }}
      bench_output: ${{ steps.run-bench.outputs.bench }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run unit tests
        id: run-tests
        run: |
          go test ./...

      - name: Run benchmarks
        id: run-bench
        run: |
          go test -bench=. ./idgen

